import type { TEliteaAssistantColors } from '@/types';

const lightColors: Required<TEliteaAssistantColors> = {
  buttonBackground: 'linear-gradient(50.4deg, #435CFF 0%, #B3BEFF 100%)',
  buttonIcon: '#FFFFFF',
  headerBackground: 'rgba(40, 69, 255, 0.25)',
  headerText: 'rgba(14, 19, 29, 1)',
  headerActionBackground: 'rgba(61, 68, 86, 0.1)',
  headerActionHoverBackground: 'rgba(61, 68, 86, 0.2)',
  headerActionActiveBackground: 'rgba(61, 68, 86, 0.2)',
  headerActionActiveColor: 'rgba(14, 19, 29, 1)',
  headerActionActiveBorder: 'rgba(203, 206, 214, 1)',
  headerActionDisabledBackground: 'rgba(61, 68, 86, 0.1)',
  headerActionDisabledColor: 'rgba(173, 175, 183, 1)',
  headerCloseBackground: 'transparent',
  headerCloseHoverBackground: 'rgba(61, 68, 86, 0.1)',
  headerCloseHoverColor: 'rgba(14, 19, 29, 1)',
  headerCloseActiveBackground: 'rgba(61, 68, 86, 0.1)',
  headerCloseActiveColor: 'rgba(119, 122, 131, 1)',
  headerCloseDisabledBackground: 'transparent',
  headerCloseDisabledColor: 'rgba(173, 175, 183, 1)',
  headerCloseIcon: 'rgba(119, 122, 131, 1)',
  chatBackground: 'rgba(255, 255, 255, 1)',
  userMessageBackground: 'rgba(141, 156, 255, 0.2)',
  userMessageText: 'rgba(14, 19, 29, 1)',
  userAvatarBackground: 'rgba(61, 68, 86, 0.15)',
  userAvatarIcon: 'rgba(255, 255, 255, 1)',
  assistantMessageBackground: '#F0F0F5',
  assistantMessageText: '#1A1A2E',
  inputBackground: 'rgba(40, 69, 255, 0.15)',
  inputText: '#1A1A2E',
  inputPlaceholder: 'rgba(173, 175, 183, 1)',
  inputBorder: '#E0E0E8',
  sendButtonBackground: 'rgba(196, 40, 221, 1)',
  sendButtonDisabledBackground: 'rgba(173, 175, 183, 1)',
  sendButtonIcon: 'rgba(255, 255, 255, 1)',
  chatWindowBorder: 'rgba(141, 156, 255, 1)',
  chatWindowShadow: '0 0.5rem 1.875rem rgba(0, 0, 0, 0.12)',
  popupBackground: 'linear-gradient(222.3deg, rgba(196, 203, 255, 1) 3.16%, rgba(245, 246, 255, 1) 100%)',
  popupBorder: 'linear-gradient(50.63deg, rgba(107, 127, 255, 1) 0%, rgba(135, 151, 255, 0.4) 100%)',
  popupText: '#1A1A2E',
  popupCloseBackground: 'rgba(61, 68, 86, 0.15)',
  popupCloseHoverBackground: 'rgba(61, 68, 86, 0.25)',
  historyDropdownBorder: 'rgba(203, 206, 213, 1)',
  historyDropdownShadow: '0 0.25rem 0.75rem rgba(0, 0, 0, 0.08)',
  historyDropdownHoverBackground: 'rgba(61, 68, 86, 0.06)',
};

const darkColors: Required<TEliteaAssistantColors> = {
  buttonBackground: 'linear-gradient(50.4deg, #C428DD 0%, #8A1B9E 100%)',
  buttonIcon: '#FFFFFF',
  headerBackground: 'rgba(245, 81, 249, 0.3)',
  headerText: 'rgba(255, 255, 255, 1)',
  headerActionBackground: 'rgba(255, 255, 255, 0.1)',
  headerActionHoverBackground: 'rgba(255, 255, 255, 0.2)',
  headerActionActiveBackground: 'rgba(14, 19, 29, 1)',
  headerActionActiveColor: 'rgba(169, 183, 193, 1)',
  headerActionActiveBorder: 'rgba(59, 62, 70, 1)',
  headerActionDisabledBackground: 'rgba(255, 255, 255, 0.1)',
  headerActionDisabledColor: 'rgba(104, 108, 118, 1)',
  headerCloseBackground: 'transparent',
  headerCloseHoverBackground: 'rgba(255, 255, 255, 0.1)',
  headerCloseHoverColor: 'rgba(255, 255, 255, 1)',
  headerCloseActiveBackground: 'rgba(255, 255, 255, 0.2)',
  headerCloseActiveColor: 'rgba(169, 183, 193, 1)',
  headerCloseDisabledBackground: 'transparent',
  headerCloseDisabledColor: 'rgba(104, 108, 118, 1)',
  headerCloseIcon: 'rgba(169, 183, 193, 1)',
  chatBackground: 'rgba(24, 31, 42, 1)',
  userMessageBackground: 'rgba(128, 60, 145, 0.6)',
  userMessageText: 'rgba(255, 255, 255, 1)',
  userAvatarBackground: 'rgba(255, 255, 255, 0.15)',
  userAvatarIcon: 'rgba(255, 255, 255, 1)',
  assistantMessageBackground: '#2A2A40',
  assistantMessageText: '#E0E0E8',
  inputBackground: 'rgba(245, 81, 249, 0.1)',
  inputText: '#E0E0E8',
  inputPlaceholder: 'rgba(104, 108, 118, 1)',
  inputBorder: '#2A2A40',
  sendButtonBackground: 'rgba(106, 232, 250, 1)',
  sendButtonDisabledBackground: 'rgba(104, 108, 118, 1)',
  sendButtonIcon: 'rgba(14, 19, 29, 1)',
  chatWindowBorder: 'rgba(245, 81, 249, 0.6)',
  chatWindowShadow: '0 0 1.875rem rgba(15, 34, 71, 0.3)',
  popupBackground: 'linear-gradient(222.3deg, #101721 3.16%, #79237b 100%)',
  popupBorder: 'linear-gradient(50.63deg, #c428dd 0%, rgba(196, 40, 221, 0.2) 100%)',
  popupText: '#FFFFFF',
  popupCloseBackground: 'rgba(255, 255, 255, 0.2)',
  popupCloseHoverBackground: 'rgba(255, 255, 255, 0.35)',
  historyDropdownBorder: 'rgba(59, 62, 70, 1)',
  historyDropdownShadow: '0 0.5rem 0.75rem rgba(0, 0, 0, 0.3)',
  historyDropdownHoverBackground: 'rgba(255, 255, 255, 0.06)',
};

const themeMap = {
  light: lightColors,
  dark: darkColors,
} as const;

export const resolveColors = (
  theme: 'light' | 'dark',
  overrides?: TEliteaAssistantColors,
): Required<TEliteaAssistantColors> => ({
  ...themeMap[theme],
  ...overrides,
});

export const colorsToCSSProperties = (colors: Required<TEliteaAssistantColors>): Record<string, string> => ({
  '--elitea-assistant-button-bg': colors.buttonBackground,
  '--elitea-assistant-button-icon': colors.buttonIcon,
  '--elitea-assistant-header-bg': colors.headerBackground,
  '--elitea-assistant-header-action-bg': colors.headerActionBackground,
  '--elitea-assistant-header-action-hover-bg': colors.headerActionHoverBackground,
  '--elitea-assistant-header-action-active-bg': colors.headerActionActiveBackground,
  '--elitea-assistant-header-action-active-color': colors.headerActionActiveColor,
  '--elitea-assistant-header-action-active-border': colors.headerActionActiveBorder,
  '--elitea-assistant-header-action-disabled-bg': colors.headerActionDisabledBackground,
  '--elitea-assistant-header-action-disabled-color': colors.headerActionDisabledColor,
  '--elitea-assistant-header-close-bg': colors.headerCloseBackground,
  '--elitea-assistant-header-close-hover-bg': colors.headerCloseHoverBackground,
  '--elitea-assistant-header-close-hover-color': colors.headerCloseHoverColor,
  '--elitea-assistant-header-close-active-bg': colors.headerCloseActiveBackground,
  '--elitea-assistant-header-close-active-color': colors.headerCloseActiveColor,
  '--elitea-assistant-header-close-disabled-bg': colors.headerCloseDisabledBackground,
  '--elitea-assistant-header-close-disabled-color': colors.headerCloseDisabledColor,
  '--elitea-assistant-header-close-icon': colors.headerCloseIcon,
  '--elitea-assistant-header-text': colors.headerText,
  '--elitea-assistant-chat-bg': colors.chatBackground,
  '--elitea-assistant-user-msg-bg': colors.userMessageBackground,
  '--elitea-assistant-user-msg-text': colors.userMessageText,
  '--elitea-assistant-user-avatar-bg': colors.userAvatarBackground,
  '--elitea-assistant-user-avatar-icon': colors.userAvatarIcon,
  '--elitea-assistant-bot-msg-bg': colors.assistantMessageBackground,
  '--elitea-assistant-bot-msg-text': colors.assistantMessageText,
  '--elitea-assistant-input-bg': colors.inputBackground,
  '--elitea-assistant-input-text': colors.inputText,
  '--elitea-assistant-input-placeholder': colors.inputPlaceholder,
  '--elitea-assistant-input-border': colors.inputBorder,
  '--elitea-assistant-send-btn-bg': colors.sendButtonBackground,
  '--elitea-assistant-send-btn-disabled-bg': colors.sendButtonDisabledBackground,
  '--elitea-assistant-send-btn-icon': colors.sendButtonIcon,
  '--elitea-assistant-window-border': colors.chatWindowBorder,
  '--elitea-assistant-window-shadow': colors.chatWindowShadow,
  '--elitea-assistant-popup-bg': colors.popupBackground,
  '--elitea-assistant-popup-border': colors.popupBorder,
  '--elitea-assistant-popup-text': colors.popupText,
  '--elitea-assistant-popup-close-bg': colors.popupCloseBackground,
  '--elitea-assistant-popup-close-hover-bg': colors.popupCloseHoverBackground,
  '--elitea-assistant-history-dropdown-border': colors.historyDropdownBorder,
  '--elitea-assistant-history-dropdown-shadow': colors.historyDropdownShadow,
  '--elitea-assistant-history-dropdown-hover-bg': colors.historyDropdownHoverBackground,
});
